import streamlit as st
import json
import os
import io
import pandas as pd
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import database as db # গুগল শিট কানেকশনের জন্য

# --- ১. গুগল শিট থেকে ডাটা লোড (এরর ছাড়া) ---
def load_savings():
    conn = db.connect_db()
    if conn:
        try:
            worksheet = conn.worksheet("Savings")
            # ডুপ্লিকেট হেডার এরর এড়াতে values দিয়ে ডাটা পড়া
            all_values = worksheet.get_all_values()
            if len(all_values) > 1:
                headers = [h.strip() if h.strip() != "" else f"empty_{i}" for i, h in enumerate(all_values[0])]
                df = pd.DataFrame(all_values[1:], columns=headers)
                valid_cols = [c for c in df.columns if not c.startswith('empty_')]
                return df[valid_cols].to_dict('records')
        except Exception as e:
            st.error(f"Error: {e}")
    return []

MONTH_MAP = {
    "Jan": "January", "Feb": "February", "Mar": "March", "Apr": "April",
    "May": "May", "Jun": "June", "Jul": "July", "Aug": "August",
    "Sep": "September", "Oct": "October", "Nov": "November", "Dec": "December"
}

def get_full_month_name(text):
    for short, full in MONTH_MAP.items():
        if short in text:
            return text.replace(short, full)
    return text

# --- ২. PDF জেনারেশন লজিক (হুবহু আপনার অরিজিনাল কোড অনুযায়ী) ---
def generate_bank_style_pdf(member):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    w, h = A4
    
    # লোগো ওয়াটারমার্ক এবং ডিজাইন (আপনার দেওয়া কোড অনুযায়ী)
    if os.path.exists("logo.png"):
        c.saveState()
        c.setFillAlpha(0.07)
        c.drawImage("logo.png", w/2 - 150, h/2 - 150, width=300, height=300, mask='auto')
        c.restoreState()
        c.drawImage("logo.png", 50, h-90, width=60, height=60, mask='auto')

    c.setStrokeColor(colors.black)
    c.setLineWidth(1)
    c.line(40, h-105, w-40, h-105) 
    
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(w/2 + 20, h-55, "AL-BARAKAH BUSINESS SOCIETY")
    c.setFont("Helvetica", 10)
    c.drawCentredString(w/2 + 20, h-75, "Barahatia, Lohagara, Chattogram")
    c.setFont("Helvetica-Bold", 9)
    c.drawCentredString(w/2 + 20, h-90, "Estd: 2025")
    
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(w/2, h-125, " MEMBER STATEMENT")
    
    c.setFont("Helvetica-Bold", 11)
    c.drawString(50, h-160, f"ACCOUNT HOLDER : {str(member['Name']).upper()}")
    c.drawString(50, h-175, f"MEMBER ID      : # {int(member['ID']):03d}")
    
    c.setFont("Helvetica", 9)
    c.drawRightString(w-50, h-160, f"Statement Date: {datetime.now().strftime('%d %b, %Y')}")
    c.drawRightString(w-50, h-175, "Status: ACTIVE")

    y = h - 215
    c.setFont("Helvetica-Bold", 11)
    c.drawString(60, y, "SL")
    c.drawString(100, y, "Description / Month")
    c.drawRightString(w-70, y, "Credit Amount (BDT)")
    c.setLineWidth(1.5)
    c.line(50, y-5, w-50, y-5)

    y -= 25
    total = 0
    sl = 1
    ignore_list = ['ID', 'Name', 'Shares', 'Share']
    
    c.setFont("Helvetica", 10)
    for k, v in member.items():
        if k not in ignore_list and v not in ['', '0', 0, None]:
            try:
                c.drawString(60, y, f"{sl:02d}")
                full_desc = get_full_month_name(k.replace("_", " "))
                c.drawString(100, y, f"Savings Deposit - {full_desc}")
                
                amt = float(str(v).replace(",", ""))
                c.drawRightString(w-70, y, f"{amt:,.2f}")
                total += amt
                sl += 1
                y -= 22
                
                c.setDash(2, 4) 
                c.setStrokeColor(colors.lightgrey)
                c.line(50, y+12, w-50, y+12)
                c.setDash(1, 0)
            except: continue

    y -= 25
    c.setStrokeColor(colors.black)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "TOTAL ACCUMULATED:")
    c.drawRightString(w-70, y, f"{total:,.2f} BDT")
    
    # আপনার অরিজিনাল ফুটার লাইন
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.gray)
    c.drawCentredString(w/2, 60, "This document is automatically generated by the system and does not require a physical signature.")
    
    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer

# --- ৩. UI ডিজাইন (আপনার অরিজিনাল কোড অনুযায়ী হুবহু) ---
def show():
    st.markdown("""
        <style>
        .ledger-header {
            background-color: #2D3748;
            padding: 15px;
            text-align: center;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .header-text { color: #F7FAFC !important; font-family: 'Segoe UI'; font-weight: bold; margin: 0; }
        div[data-testid="stTextInput"] label { color: #4A5568 !important; font-weight: bold; }
        .total-box {
            text-align: right;
            padding: 10px;
            background-color: #F7FAFC;
            border: 1px solid #CBD5E0;
            border-radius: 5px;
            margin-top: 10px;
        }
        </style>
    """, unsafe_allow_html=True)

    st.markdown('<div class="ledger-header"><h2 class="header-text">📊 MEMBER LEDGER DASHBOARD</h2></div>', unsafe_allow_html=True)

    with st.container():
        m_id = st.text_input("Search Member ID:", placeholder="Enter ID and press Enter...")
        
        if m_id:
            # সরাসরি গুগল শিট থেকে ডাটা আনা
            data = load_savings()
            member = next((s for s in data if str(s['ID']) == m_id), None)
            
            if member:
                st.markdown(f"<h3 style='color:#2B6CB0;'>👤 ACCOUNT: {member['Name'].upper()} (ID: {member['ID']})</h3>", unsafe_allow_html=True)
                
                table_data = []
                total = 0
                idx = 1
                ignore_list = ['ID', 'Name', 'Shares', 'Share']
                
                for k, v in member.items():
                    if k not in ignore_list and v not in ['', '0', 0, None]:
                        try:
                            val = float(str(v).replace(",", ""))
                            full_desc = get_full_month_name(k.replace("_", " "))
                            table_data.append([f"{idx:02d}", f"Savings - {full_desc}", f"{val:,.2f}"])
                            total += val
                            idx += 1
                        except: continue
                
                df = pd.DataFrame(table_data, columns=["SL", "Transaction Month/Description", "Deposit Amount (BDT)"])
                st.table(df)

                st.markdown(f"""
                    <div class="total-box">
                        <h3 style="color:#2F855A; margin:0;">Total Accumulated: {total:,.2f} BDT</h3>
                    </div>
                """, unsafe_allow_html=True)

                st.divider()
                pdf_bytes = generate_bank_style_pdf(member)
                st.download_button(
                    label="📥 DOWNLOAD MEMBER STATEMENT",
                    data=pdf_bytes,
                    file_name=f"Statement_{member['ID']}.pdf",
                    mime="application/pdf",
                    use_container_width=True
                )
            else:
                st.error("❌ ID Not Found!")
