import os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from datetime import datetime

def generate_bank_style_pdf(member):
    path = f"/tmp/Statement_{member['ID']}.pdf"
    c = canvas.Canvas(path, pagesize=A4)
    w, h = A4

    if os.path.exists("logo.png"):
        c.saveState()
        c.setFillAlpha(0.07)
        c.drawImage("logo.png", w/2-150, h/2-150, 300, 300, mask="auto")
        c.restoreState()
        c.drawImage("logo.png", 50, h-90, 60, 60, mask="auto")

    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(w/2+20, h-55, "AL-BARAKAH BUSINESS SOCIETY")
    c.setFont("Helvetica", 10)
    c.drawCentredString(w/2+20, h-75, "Barahatia, Lohagara, Chattogram")
    c.setFont("Helvetica-Bold", 9)
    c.drawCentredString(w/2+20, h-90, "Estd: 2025")

    c.line(40, h-105, w-40, h-105)
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(w/2, h-125, "MEMBER STATEMENT")

    c.setFont("Helvetica-Bold", 11)
    c.drawString(50, h-160, f"ACCOUNT HOLDER : {member['Name'].upper()}")
    c.drawString(50, h-175, f"MEMBER ID : # {int(member['ID']):03d}")

    c.setFont("Helvetica", 9)
    c.drawRightString(w-50, h-160, f"Statement Date: {datetime.now().strftime('%d %b, %Y')}")
    c.drawRightString(w-50, h-175, "Status: ACTIVE")

    y = h - 215
    c.setFont("Helvetica-Bold", 11)
    c.drawString(60, y, "SL")
    c.drawString(100, y, "Description / Month")
    c.drawRightString(w-70, y, "Credit Amount (BDT)")
    c.line(50, y-5, w-50, y-5)
    y -= 25

    total, sl = 0, 1
    c.setFont("Helvetica", 10)

    for k, v in member.items():
        if k not in ['ID', 'Name', 'Shares'] and v not in ['', '0', None]:
            val = float(str(v).replace(",", ""))
            c.drawString(60, y, f"{sl:02d}")
            c.drawString(100, y, f"Savings Deposit - {k.replace('_',' ')}")
            c.drawRightString(w-70, y, f"{val:,.2f}")
            total += val
            sl += 1
            y -= 22

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y-20, "TOTAL ACCUMULATED:")
    c.drawRightString(w-70, y-20, f"{total:,.2f} BDT")

    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.gray)
    c.drawCentredString(w/2, 60,
        "This document is automatically generated by the system and does not require a physical signature."
    )

    c.save()
    return path
